name: release
on:
  push:
    branches:
      - main
      - test

permissions:
  id-token: write  # Required for Trusted Publishing: https://docs.npmjs.com/trusted-publishers
  contents: read

jobs:
  build-and-release:
    name: 'Build project, run CI checks and publish new release'
    uses: fingerprintjs/dx-team-toolkit/.github/workflows/release-typescript-project.yml@v1
    with:
      appId: ${{ vars.APP_ID }}
      useTrustedPublishing: true
    secrets:
      APP_PRIVATE_KEY: ${{ secrets.APP_PRIVATE_KEY }}
      NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
